# Generated by Django 4.2 on 2024-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rental_images/')),
                ('transport_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Scooter', 'Scooter'), ('Motorbike', 'Motorbike')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_model', models.CharField(choices=[('Toyota Corolla', 'Toyota Corolla'), ('Honda Civic', 'Honda Civic'), ('Ford Fiesta', 'Ford Fiesta'), ('BMW 3 Series', 'BMW 3 Series'), ('Kawasaki Ninja', 'Kawasaki Ninja')], max_length=100)),
                ('vehicle_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
