# Generated by Django 4.2 on 2024-10-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_flight_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='available_places',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='image',
        ),
    ]
