# Generated by Django 4.2 on 2024-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0003_remove_flight_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flights/'),
        ),
    ]
