# Generated by Django 4.2 on 2024-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('price_per_place', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_places', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
