# Generated by Django 4.2 on 2024-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='accommodation_images/')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_of_accommodation', models.CharField(choices=[('Hotel Room', 'Hotel Room'), ('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa')], max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.CharField(choices=[('Wi-Fi', 'Wi-Fi'), ('Pool', 'Pool'), ('Parking', 'Parking'), ('Gym', 'Gym'), ('Breakfast', 'Breakfast'), ('Air Conditioning', 'Air Conditioning')], max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
