# Generated by Django 4.2 on 2024-10-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="accommodation", name="city",),
    ]
