# Generated by Django 4.2 on 2024-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0002_remove_accommodation_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="ratings",
            field=models.JSONField(default=list),
        ),
    ]
