# Generated by Django 4.2 on 2024-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0005_alter_accommodation_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
