# Generated by Django 4.2 on 2024-10-27 12:07

import Person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Person.models.validateCin]),
        ),
    ]
