# Generated by Django 4.2 on 2024-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_alter_person_options_person_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='keyword',
            field=models.CharField(default='p', max_length=10),
        ),
    ]
