# Generated by Django 4.2 on 2024-10-29 19:35

import Person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0006_alter_person_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[Person.models.validateCin]),
        ),
        migrations.AlterField(
            model_name='person',
            name='keyword',
            field=models.CharField(default=' ', max_length=8),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
