# Generated by Django 4.2 on 2024-10-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Flight', '0001_initial'),
        ('Accommodation', '0001_initial'),
        ('RentalTransport', '0001_initial'),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reservation', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('cin', models.PositiveIntegerField()),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('nb_days', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('rental_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='RentalTransport.rentaltransport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reservation', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('cin', models.PositiveIntegerField()),
                ('seat_class', models.CharField(choices=[('Economique', 'Economique'), ('Affaires', 'Affaires'), ('Première', 'Première')], max_length=50)),
                ('seat_numbers', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Flight.flight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reservation', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('cin', models.PositiveIntegerField()),
                ('seat_numbers', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reservation', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('cin', models.PositiveIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('night_numbers', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Accommodation.accommodation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
