# Generated by Django 4.2 on 2024-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_travelers',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
