# Generated by Django 4.2 on 2024-10-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_reservation_remove_eventreservation_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
