# Generated by Django 4.2 on 2024-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_alter_reservation_number_of_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='passport_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
