# Generated by Django 4.2 on 2024-10-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
