# Generated by Django 4.2 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0004_reservation_reservinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
